<?php

namespace Brainstrap\CoreBundle\Repository\Session;

use Doctrine\ORM\EntityRepository;

/**
 * SessionStatusCompletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionStatusRepository extends EntityRepository
{
}
