brainstrap_oauth_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: BrainstrapOAuthBundle:Security:login }

brainstrap_oauth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: BrainstrapOAuthBundle:Security:loginCheck }