company:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\CompanyController

cart:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\CartController

client:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\ClientController

session_simple:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\SimpleSessionController

session_group:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\Session\GroupSessionController

session_status_completed:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\SessionStatusController

rate_time:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\Rate\TimeController

rate_time_collection:
    type: rest
    resource: Brainstrap\CoreBundle\Controller\Rate\CollectionTimeController

# user:
#     type: rest
#     parent: organisation
#     resource: Brainstrap\CoreBundle\Controller\UserController