parameters:
#    brainstrap_core.example.class: Brainstrap\CoreBundle\Example

services:
#    brainstrap_core.example:
#        class: %brainstrap_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
