<?php
/**
 * Created by PhpStorm.
 * User: karmis
 * Date: 26.02.14
 * Time: 1:22
 */

namespace Brainstrap\OAuthBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}